// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5jTOgTgsDOqC-xJBGWb2VXH7V8uJqs-Q',
    appId: '1:964809557211:android:d3f28acb815446778b38fe',
    messagingSenderId: '964809557211',
    projectId: 'bookingtourflutter-bafe8',
    storageBucket: 'bookingtourflutter-bafe8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6LYH53V0LJ4Uc4_p4t3JdLihEYZCdU6k',
    appId: '1:964809557211:ios:298e71f22d130fd28b38fe',
    messagingSenderId: '964809557211',
    projectId: 'bookingtourflutter-bafe8',
    storageBucket: 'bookingtourflutter-bafe8.firebasestorage.app',
    androidClientId:
        '964809557211-a8p4s4uq5aljc3spohpatn1o8v150sc6.apps.googleusercontent.com',
    iosClientId:
        '964809557211-k6tp4h4cde7rinqk11nddl4n1qm708pt.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookingTourFlutter',
  );
}
